version = 1

[[annotations]]
path = "**"
SPDX-FileCopyrightText = [
    "Copyright (c) 2012-2014 Giampaolo Rodola",
    "Copyright (c) 2025 Stephen Arnold",
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "toxfile.py"
SPDX-FileCopyrightText = "Copyright (c) 2023 Masen Furer"
SPDX-License-Identifier = "MIT"
